env1:
  name: "env1_Full_Info_Non_Rand_Size25_Rand_Starting_Pose_Obstacle"
  base_steps: 10000000
  number_agents: 1
  random_number_agents : false
  sensor: "full information"
  sensor_range: 2
  size: 6
  min_size: 6
  random_size: true
  obstacles_random: false
  number_obstacles: 2
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: false