env1:
  name: "env1_Full_Info_Non_Rand_Size25_Rand_Starting_Pose_Obstacle"
  base_steps: 10000000
  number_agents: 1
  random_number_agents : false
  sensor: "full information"
  sensor_range: 2
  size: 32
  min_size: 32
  random_size: false
  obstacles_random: true
  number_obstacles: 0
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'maps/map4.yaml'
  random_coverage : false
  dataset_path: 'empty'
  load_state: false
  load_random: false
  chi_agents: 0.5
  chi_cov: 0.15