env1:
  name: "env1"
  base_steps: 2000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 3
  size: 5
  min_size: 4
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [0,4]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: false
  chi_agents: 0.5
  chi_cov: 0.15
env2:
  name: "env2"
  base_steps: 2000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 3
  size: 10
  min_size: 5
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [9,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: false
  chi_agents: 0.5
  chi_cov: 0.15
env3:
  name: "env3"
  base_steps: 2000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 3
  size: 15
  min_size: 10
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [14,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: false
  chi_agents: 0.5
  chi_cov: 0.15
env4:
  name: "env4"
  base_steps: 2000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 3
  size: 19
  min_size: 9
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: false
  chi_agents: 0.5
  chi_cov: 0.15
env5:
  name: "env5"
  base_steps: 4000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 4
  size: 25
  min_size: 15
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: true
  chi_agents: 0.5
  chi_cov: 0.15
env6:
  name: "env6"
  base_steps: 4000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 4
  size: 30
  min_size: 20
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : false
  dataset_path: 'empty'
  load_state: false
  load_random: true
  chi_agents: 0.5
  chi_cov: 0.15
env7:
  name: "env7"
  base_steps: 5000000
  number_agents: 2
  random_number_agents : true
  sensor: "full information"
  sensor_range: 4
  size: 40
  min_size: 20
  random_size: true
  obstacles_random: true
  number_obstacles: 5
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : false
  dataset_path: 'empty'
  load_state: false
  load_random: true
  chi_agents: 0.5
  chi_cov: 0.15
